version: 2.17
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: update-npm
          command: 'sudo npm install -g @angular/cli > /dev/null'
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Push changes to another branch
          command: git push -f origin main:deploy;
      - run:
          name: Checkout to deploy branch
          command: git checkout deploy;
      - run:
          name: Build angular dist
          command: npm i;
      - run:
          name: Build angular dist
          command: npm run deploy-build;
      - run:
          name: Commit builded package
          command: git add .;
      - run:
          name: Commit
          command: git commit -m 'chore deploy';
      - run:
          name: Push the changes
          command: git push;

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
